// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { useCallback, useEffect } from 'react';
import {
  ActivityIndicator,
  FlatList,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useLocalSearchParams, useNavigation } from 'expo-router';
import { useAccountsStore } from '@/stores/accountsStore';
import { useTransactionsStore } from '@/stores/transactionsStore';
import type { Transaction } from '@/types/index';
import { TransactionItem } from '@/components/ui/TransactionItem';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { LoadingState } from '@/components/ui/LoadingState';
import { OfflineBanner } from '@/components/ui/OfflineBanner';

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export default function AccountScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const navigation = useNavigation();

  const { getAccountById, isOffline } = useAccountsStore();
  const {
    fetchTransactions,
    loadMoreTransactions,
    getTransactions,
    getPagination,
    isLoading: isLoadingFn,
    errorByAccount,
  } = useTransactionsStore();

  const account = getAccountById(id);
  const transactions = getTransactions(id);
  const pagination = getPagination(id);
  const isLoading = isLoadingFn(id);
  const error = errorByAccount[id] ?? null;

  // Set header title to account name
  useEffect(() => {
    if (account) {
      navigation.setOptions({ title: account.name });
    }
  }, [account, navigation]);

  // Initial load
  useEffect(() => {
    if (id) {
      void fetchTransactions(id, 1);
    }
  }, [id, fetchTransactions]);

  const handleRetry = useCallback(() => {
    void fetchTransactions(id, 1);
  }, [id, fetchTransactions]);

  const handleEndReached = useCallback(() => {
    if (pagination?.hasNextPage && !isLoading) {
      void loadMoreTransactions(id);
    }
  }, [id, pagination, isLoading, loadMoreTransactions]);

  const formatBalance = (amount: number): string =>
    `S/ ${amount.toLocaleString('es-PE', { minimumFractionDigits: 2 })}`;

  // ---- Loading (first page) ----
  if (isLoading && transactions.length === 0) {
    return (
      <View style={styles.flex}>
        <LoadingState message="Cargando movimientos…" />
      </View>
    );
  }

  // ---- Error (no data at all) ----
  if (error !== null && transactions.length === 0) {
    return (
      <View style={styles.flex}>
        <ErrorState message={error} onRetry={handleRetry} />
      </View>
    );
  }

  return (
    <View style={styles.flex}>
      <OfflineBanner visible={isOffline} />

      <FlatList<Transaction>
        data={transactions}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => <TransactionItem transaction={item} />}
        ListHeaderComponent={
          account ? (
            <View style={styles.balanceHeader}>
              <Text style={styles.balanceLabel}>Saldo disponible</Text>
              <Text style={styles.balanceAmount}>{formatBalance(account.balance)}</Text>
            </View>
          ) : null
        }
        ListEmptyComponent={
          <EmptyState
            message="Sin movimientos"
            subtitle="Todavía no hay transacciones en esta cuenta."
          />
        }
        ListFooterComponent={
          isLoading && transactions.length > 0 ? (
            <View style={styles.footer}>
              <ActivityIndicator color="#2563eb" />
            </View>
          ) : null
        }
        onEndReached={handleEndReached}
        onEndReachedThreshold={0.3}
        contentContainerStyle={transactions.length === 0 ? styles.flex : undefined}
      />
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  balanceHeader: {
    backgroundColor: '#2563eb',
    paddingHorizontal: 16,
    paddingVertical: 24,
    marginBottom: 8,
  },
  balanceLabel: {
    fontSize: 13,
    color: '#bfdbfe',
    marginBottom: 4,
    fontWeight: '500',
  },
  balanceAmount: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
  },
  footer: {
    paddingVertical: 16,
    alignItems: 'center',
  },
});
