// Generated by GentleIA (OpenCode) — Phase 2: Auth

import * as SecureStore from 'expo-secure-store';
import type { TokenResponse, User } from '@/types/index';
import { apiClient } from '../api/client';
import { tokenStore } from './tokenStore';
import { generateCodeVerifier, generateCodeChallenge, generateState } from './pkce';

// ---------------------------------------------------------------------------
// SecureStore keys — never change these or stored sessions will be orphaned
// ---------------------------------------------------------------------------

const KEYS = {
  ACCESS_TOKEN: 'bankgo.access_token',
  REFRESH_TOKEN: 'bankgo.refresh_token',
  EXPIRES_AT: 'bankgo.expires_at',
} as const;

// ---------------------------------------------------------------------------
// authService
// ---------------------------------------------------------------------------

export const authService = {
  /**
   * Executes a PKCE-based login flow against the mock backend.
   * Persists tokens to SecureStore and hydrates the in-memory tokenStore.
   */
  async login(email: string, password: string): Promise<void> {
    const verifier = await generateCodeVerifier();
    const challenge = await generateCodeChallenge(verifier);
    const state = await generateState();

    const response = await apiClient.post<TokenResponse>('/auth/token', {
      email,
      password,
      code_challenge: challenge,
      code_challenge_method: 'S256',
      state,
    });

    const expiresAt = Date.now() + response.expires_in * 1000;

    // Persist to SecureStore — tokens never touch AsyncStorage
    await SecureStore.setItemAsync(KEYS.ACCESS_TOKEN, response.access_token);
    await SecureStore.setItemAsync(KEYS.REFRESH_TOKEN, response.refresh_token);
    await SecureStore.setItemAsync(KEYS.EXPIRES_AT, String(expiresAt));

    // Hydrate the in-memory store so apiClient can use the token immediately
    tokenStore.setTokens(response.access_token, response.refresh_token);

    // Never log actual token values
    console.warn('[Auth] Login completed');
  },

  /**
   * Clears all persisted tokens and the in-memory store.
   */
  async logout(): Promise<void> {
    await SecureStore.deleteItemAsync(KEYS.ACCESS_TOKEN);
    await SecureStore.deleteItemAsync(KEYS.REFRESH_TOKEN);
    await SecureStore.deleteItemAsync(KEYS.EXPIRES_AT);

    tokenStore.clear();

    console.warn('[Auth] Logout completed');
  },

  /**
   * Returns true if there is a non-expired access token in memory.
   */
  isAuthenticated(): boolean {
    return tokenStore.hasToken();
  },

  /**
   * Fetches the current user from /auth/me.
   * Requires an active session (login must have been called first).
   */
  async getUser(): Promise<User> {
    return apiClient.get<User>('/auth/me');
  },

  /**
   * Restores a persisted session from SecureStore.
   * Returns true if the session was successfully restored.
   */
  async restoreSession(): Promise<boolean> {
    const [accessToken, refreshToken, expiresAtStr] = await Promise.all([
      SecureStore.getItemAsync(KEYS.ACCESS_TOKEN),
      SecureStore.getItemAsync(KEYS.REFRESH_TOKEN),
      SecureStore.getItemAsync(KEYS.EXPIRES_AT),
    ]);

    if (!accessToken || !refreshToken || !expiresAtStr) {
      return false;
    }

    const expiresAt = parseInt(expiresAtStr, 10);
    if (isNaN(expiresAt) || expiresAt <= Date.now()) {
      // Tokens expired — clean up
      await authService.logout();
      return false;
    }

    tokenStore.setTokens(accessToken, refreshToken);
    return true;
  },
};
