// Generated by GentleIA (OpenCode) — Phase 2: Auth

import * as Crypto from 'expo-crypto';

// ---------------------------------------------------------------------------
// URL-safe base64 encoding (RFC 4648 §5) — no padding
// ---------------------------------------------------------------------------

function toBase64Url(buffer: Uint8Array): string {
  // Convert Uint8Array to a binary string, then btoa
  let binary = '';
  for (let i = 0; i < buffer.length; i++) {
    binary += String.fromCharCode(buffer[i]!);
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

// ---------------------------------------------------------------------------
// generateCodeVerifier — RFC 7636 §4.1
// 43-128 URL-safe base64 chars, generated from cryptographic random bytes
// ---------------------------------------------------------------------------

export async function generateCodeVerifier(): Promise<string> {
  // 32 bytes → 43 chars in base64url (≥ 43-char minimum from the RFC)
  const bytes = Crypto.getRandomBytes(32);
  return toBase64Url(bytes);
}

// ---------------------------------------------------------------------------
// generateCodeChallenge — RFC 7636 §4.2
// SHA-256 of the verifier, base64url-encoded (no padding)
// ---------------------------------------------------------------------------

export async function generateCodeChallenge(verifier: string): Promise<string> {
  const digest = await Crypto.digest(
    Crypto.CryptoDigestAlgorithm.SHA256,
    // digest() accepts ArrayBuffer — encode the verifier string as UTF-8
    new TextEncoder().encode(verifier),
  );
  return toBase64Url(new Uint8Array(digest));
}

// ---------------------------------------------------------------------------
// generateState — opaque CSRF token, 32 hex chars (16 bytes)
// ---------------------------------------------------------------------------

export async function generateState(): Promise<string> {
  const bytes = Crypto.getRandomBytes(16);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}
