// Generated by GentleIA (OpenCode) — Phase 1: Mock API

/**
 * In-memory token store for development / test.
 * In production this would use SecureStore (expo-secure-store).
 * The store NEVER logs the actual token value — only redacted references.
 */

let _accessToken: string | null = null;
let _refreshToken: string | null = null;

export const tokenStore = {
  getAccessToken(): string | null {
    return _accessToken;
  },

  getRefreshToken(): string | null {
    return _refreshToken;
  },

  setTokens(access: string, refresh: string): void {
    _accessToken = access;
    _refreshToken = refresh;
    // Never log the actual values — only existence
    console.debug('[tokenStore] tokens set: access=[REDACTED], refresh=[REDACTED]');
  },

  clear(): void {
    _accessToken = null;
    _refreshToken = null;
    console.debug('[tokenStore] tokens cleared');
  },

  hasToken(): boolean {
    return _accessToken !== null;
  },
};
