// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards (updated from Phase 2: Auth)

import { useEffect } from 'react';
import { TouchableOpacity, Text, StyleSheet } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { useAuthStore } from '@/stores/authStore';

// ---------------------------------------------------------------------------
// Protected layout — redirects to login if not authenticated
// ---------------------------------------------------------------------------

export default function AppLayout() {
  const { isAuthenticated, isLoading, logout } = useAuthStore();
  const router = useRouter();

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.replace('/(auth)/login');
    }
  }, [isAuthenticated, isLoading, router]);

  async function handleLogout() {
    await logout();
    router.replace('/(auth)/login');
  }

  return (
    <Stack
      screenOptions={{
        headerStyle: { backgroundColor: '#2563eb' },
        headerTintColor: '#ffffff',
        headerTitleStyle: { fontWeight: '700' },
        headerTitle: 'BankGo',
        headerRight: () => (
          <TouchableOpacity onPress={handleLogout} style={styles.logoutButton}>
            <Text style={styles.logoutText}>Salir</Text>
          </TouchableOpacity>
        ),
      }}
    >
      <Stack.Screen name="dashboard" options={{ title: 'BankGo' }} />
      <Stack.Screen name="transfer" options={{ title: 'Transferir' }} />
      <Stack.Screen name="cards" options={{ title: 'Mis tarjetas' }} />
    </Stack>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
});
