// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards

import { useCallback, useEffect, useState } from 'react';
import {
  FlatList,
  RefreshControl,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useCardsStore } from '@/stores/cardsStore';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { ConfirmationDialog } from '@/components/ui/ConfirmationDialog';
import type { Card } from '@/types/index';

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export default function CardsScreen() {
  const { cards, isLoading, error, fetchCards, toggleCardFreeze } = useCardsStore();

  // Estado para el diálogo de confirmación
  const [dialogVisible, setDialogVisible] = useState(false);
  const [selectedCard, setSelectedCard] = useState<Card | null>(null);
  const [isToggling, setIsToggling] = useState(false);

  useEffect(() => {
    void fetchCards();
  }, [fetchCards]);

  const handleRefresh = useCallback(() => {
    void fetchCards();
  }, [fetchCards]);

  function handleFreezePress(card: Card) {
    setSelectedCard(card);
    setDialogVisible(true);
  }

  function handleDialogCancel() {
    setDialogVisible(false);
    setSelectedCard(null);
  }

  async function handleDialogConfirm() {
    if (selectedCard === null) return;

    setIsToggling(true);
    await toggleCardFreeze(selectedCard.id);
    setIsToggling(false);
    setDialogVisible(false);
    setSelectedCard(null);
  }

  // ---- Loading inicial ----
  if (isLoading && cards.length === 0) {
    return (
      <View style={styles.flex}>
        <LoadingState message="Cargando tus tarjetas…" />
      </View>
    );
  }

  // ---- Error (sin datos) ----
  if (error !== null && cards.length === 0) {
    return (
      <View style={styles.flex}>
        <ErrorState message={error} onRetry={handleRefresh} />
      </View>
    );
  }

  const dialogTitle = selectedCard?.frozen ? 'Descongelar tarjeta' : 'Congelar tarjeta';
  const dialogMessage = selectedCard?.frozen
    ? `¿Querés descongelar la tarjeta terminada en ${selectedCard.lastFour}? Podrás usarla nuevamente.`
    : `¿Querés congelar la tarjeta terminada en ${selectedCard?.lastFour ?? ''}? No podrás realizar pagos con ella mientras esté congelada.`;

  return (
    <View style={styles.flex}>
      <FlatList
        data={cards}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <CardItem card={item} onToggleFreeze={() => handleFreezePress(item)} />
        )}
        ListHeaderComponent={
          <View style={styles.header}>
            <Text style={styles.title}>Mis tarjetas</Text>
            <Text style={styles.subtitle}>{cards.length} tarjeta{cards.length !== 1 ? 's' : ''} registrada{cards.length !== 1 ? 's' : ''}</Text>
          </View>
        }
        ListEmptyComponent={
          <EmptyState
            message="No tenés tarjetas registradas"
            subtitle="Contactá a soporte para agregar una tarjeta."
          />
        }
        refreshControl={
          <RefreshControl
            refreshing={isLoading}
            onRefresh={handleRefresh}
            tintColor="#2563eb"
          />
        }
        contentContainerStyle={cards.length === 0 ? styles.flex : styles.listContent}
      />

      <ConfirmationDialog
        visible={dialogVisible}
        title={dialogTitle}
        message={dialogMessage}
        onConfirm={() => void handleDialogConfirm()}
        onCancel={handleDialogCancel}
        loading={isToggling}
      />
    </View>
  );
}

// ---------------------------------------------------------------------------
// CardItem
// ---------------------------------------------------------------------------

interface CardItemProps {
  card: Card;
  onToggleFreeze: () => void;
}

function CardItem({ card, onToggleFreeze }: CardItemProps) {
  const brandLabel = card.brand === 'visa' ? 'Visa' : 'Mastercard';
  const statusLabel = card.frozen ? 'Congelada' : 'Activa';
  const buttonLabel = card.frozen ? 'Descongelar' : 'Congelar';
  const cardBackground = card.frozen ? '#64748b' : '#1e3a8a';

  return (
    <View style={styles.cardWrapper}>
      <View style={[styles.card, { backgroundColor: cardBackground }]}>
        {/* Encabezado */}
        <View style={styles.cardHeader}>
          <Text style={styles.brandText}>{brandLabel}</Text>
          <View
            style={[
              styles.statusBadge,
              card.frozen ? styles.statusFrozen : styles.statusActive,
            ]}
          >
            <Text style={styles.statusBadgeText}>{statusLabel}</Text>
          </View>
        </View>

        {/* Número */}
        <Text style={styles.cardNumber}>•••• •••• •••• {card.lastFour}</Text>

        {/* Pie */}
        <View style={styles.cardFooter}>
          <View>
            <Text style={styles.cardLabel}>Vencimiento</Text>
            <Text style={styles.cardValue}>{card.expiresAt}</Text>
          </View>

          <TouchableOpacity
            style={[
              styles.freezeButton,
              card.frozen ? styles.unfreezeButton : styles.freezeButtonActive,
            ]}
            onPress={onToggleFreeze}
            accessibilityRole="button"
            accessibilityLabel={`${buttonLabel} tarjeta terminada en ${card.lastFour}`}
          >
            <Text
              style={[
                styles.freezeButtonText,
                card.frozen && styles.unfreezeButtonText,
              ]}
            >
              {card.frozen ? '❄ ' : '🔒 '}{buttonLabel}
            </Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  listContent: {
    paddingBottom: 32,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 8,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748b',
  },
  cardWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  card: {
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  brandText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 1,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.25)',
  },
  statusFrozen: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  cardNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 3,
    marginBottom: 24,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  cardLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  cardValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  freezeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  freezeButtonActive: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  unfreezeButton: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  freezeButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  unfreezeButtonText: {
    color: '#ffffff',
  },
});
