// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { useCallback, useEffect } from 'react';
import {
  FlatList,
  RefreshControl,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useAuthStore } from '@/stores/authStore';
import { useAccountsStore } from '@/stores/accountsStore';
import type { Account } from '@/types/index';
import { AccountCard } from '@/components/ui/AccountCard';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { LoadingState } from '@/components/ui/LoadingState';
import { OfflineBanner } from '@/components/ui/OfflineBanner';

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export default function DashboardScreen() {
  const router = useRouter();
  const { user } = useAuthStore();
  const { accounts, isLoading, error, isOffline, fetchAccounts } = useAccountsStore();

  useEffect(() => {
    void fetchAccounts();
  }, [fetchAccounts]);

  const handleRefresh = useCallback(() => {
    void fetchAccounts();
  }, [fetchAccounts]);

  const handleAccountPress = useCallback(
    (account: Account) => {
      router.push(`/(app)/account/${account.id}`);
    },
    [router],
  );

  const firstName = user?.name?.split(' ')[0] ?? 'usuario';

  // ---- Loading ----
  if (isLoading && accounts.length === 0) {
    return (
      <View style={styles.flex}>
        <LoadingState message="Cargando tus cuentas…" />
      </View>
    );
  }

  // ---- Error (no cache) ----
  if (error !== null && accounts.length === 0) {
    return (
      <View style={styles.flex}>
        <ErrorState message={error} onRetry={handleRefresh} />
      </View>
    );
  }

  return (
    <View style={styles.flex}>
      <OfflineBanner visible={isOffline} />

      <FlatList
        data={accounts}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => (
          <AccountCard account={item} onPress={() => handleAccountPress(item)} />
        )}
        ListHeaderComponent={
          <View style={styles.header}>
            <Text style={styles.greeting}>Bienvenida, {firstName} 👋</Text>
            <Text style={styles.subtitle}>Resumen de tus cuentas</Text>
          </View>
        }
        ListEmptyComponent={
          <EmptyState
            message="No tenés cuentas registradas"
            subtitle="Contactá a soporte para agregar una cuenta."
          />
        }
        refreshControl={
          <RefreshControl
            refreshing={isLoading}
            onRefresh={handleRefresh}
            tintColor="#2563eb"
          />
        }
        contentContainerStyle={accounts.length === 0 ? styles.flex : styles.listContent}
      />
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  listContent: {
    paddingBottom: 32,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 12,
  },
  greeting: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748b',
  },
});
