// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards

import { useEffect } from 'react';
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useTransferStore } from '@/stores/transferStore';
import { useAccountsStore } from '@/stores/accountsStore';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { InAppNotification } from '@/components/ui/InAppNotification';
import { seedBeneficiaries } from '@/services/api/seed';
import type { Beneficiary } from '@/types/index';

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export default function TransferScreen() {
  const router = useRouter();
  const {
    step,
    fromAccountId,
    beneficiaryId,
    amount,
    currency,
    description,
    pendingTransfer,
    isSubmitting,
    error,
    notification,
    setFormData,
    validate,
    submitTransfer,
    confirmTransfer,
    resetTransfer,
    clearNotification,
  } = useTransferStore();

  const { accounts, fetchAccounts } = useAccountsStore();

  useEffect(() => {
    if (accounts.length === 0) {
      void fetchAccounts();
    }
  }, [accounts.length, fetchAccounts]);

  // ---------------------------------------------------------------------------
  // Step 1 — Formulario
  // ---------------------------------------------------------------------------

  if (step === 'form') {
    const validationError = error;

    function handleReview() {
      const err = validate();
      if (err !== null) {
        setFormData({});  // trigger re-render with the current error surfaced below
        useTransferStore.setState({ error: err });
        return;
      }
      void submitTransfer();
    }

    const selectedBeneficiary = seedBeneficiaries.find((b) => b.id === beneficiaryId);
    const selectedAccount = accounts.find((a) => a.id === fromAccountId);

    return (
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      >
        <ScrollView
          style={styles.flex}
          contentContainerStyle={styles.scrollContent}
          keyboardShouldPersistTaps="handled"
        >
          <Text style={styles.screenTitle}>Nueva transferencia</Text>

          {/* Cuenta origen */}
          <Text style={styles.label}>Cuenta de origen</Text>
          <View style={styles.optionGroup}>
            {accounts.map((account) => (
              <TouchableOpacity
                key={account.id}
                style={[
                  styles.optionItem,
                  fromAccountId === account.id && styles.optionItemSelected,
                ]}
                onPress={() => setFormData({ fromAccountId: account.id })}
                accessibilityRole="radio"
                accessibilityState={{ checked: fromAccountId === account.id }}
              >
                <View>
                  <Text style={styles.optionTitle}>{account.name}</Text>
                  <Text style={styles.optionSubtitle}>
                    Saldo: {account.currency} {account.balance.toLocaleString('es-PE', { minimumFractionDigits: 2 })}
                  </Text>
                </View>
                {fromAccountId === account.id && (
                  <Text style={styles.checkmark}>✓</Text>
                )}
              </TouchableOpacity>
            ))}
          </View>

          {/* Beneficiario */}
          <Text style={styles.label}>Beneficiario</Text>
          <View style={styles.optionGroup}>
            {seedBeneficiaries.map((ben: Beneficiary) => (
              <TouchableOpacity
                key={ben.id}
                style={[
                  styles.optionItem,
                  beneficiaryId === ben.id && styles.optionItemSelected,
                ]}
                onPress={() => setFormData({ beneficiaryId: ben.id })}
                accessibilityRole="radio"
                accessibilityState={{ checked: beneficiaryId === ben.id }}
              >
                <View>
                  <Text style={styles.optionTitle}>{ben.name}</Text>
                  <Text style={styles.optionSubtitle}>
                    {ben.bank} · {ben.iban.slice(-8)}
                  </Text>
                </View>
                {beneficiaryId === ben.id && (
                  <Text style={styles.checkmark}>✓</Text>
                )}
              </TouchableOpacity>
            ))}
          </View>

          {/* Monto */}
          <Text style={styles.label}>Monto</Text>
          <TextInput
            style={styles.input}
            value={amount}
            onChangeText={(text) => setFormData({ amount: text })}
            placeholder="0.00"
            keyboardType="decimal-pad"
            placeholderTextColor="#94a3b8"
            accessibilityLabel="Monto de la transferencia"
          />

          {/* Moneda */}
          <Text style={styles.label}>Moneda</Text>
          <View style={styles.currencyRow}>
            {(['PEN', 'USD'] as const).map((c) => (
              <TouchableOpacity
                key={c}
                style={[
                  styles.currencyButton,
                  currency === c && styles.currencyButtonSelected,
                ]}
                onPress={() => setFormData({ currency: c })}
                accessibilityRole="radio"
                accessibilityState={{ checked: currency === c }}
              >
                <Text
                  style={[
                    styles.currencyText,
                    currency === c && styles.currencyTextSelected,
                  ]}
                >
                  {c}
                </Text>
              </TouchableOpacity>
            ))}
          </View>

          {/* Descripción */}
          <Text style={styles.label}>Descripción (opcional)</Text>
          <TextInput
            style={[styles.input, styles.inputMultiline]}
            value={description}
            onChangeText={(text) => setFormData({ description: text })}
            placeholder="Ej: Pago de deuda"
            placeholderTextColor="#94a3b8"
            multiline
            numberOfLines={2}
            accessibilityLabel="Descripción de la transferencia"
          />

          {/* Error de validación */}
          {validationError !== null && validationError !== undefined && (
            <View style={styles.errorBox}>
              <Text style={styles.errorText}>{validationError}</Text>
            </View>
          )}

          {/* Preview cuenta + beneficiario seleccionados */}
          {selectedAccount !== undefined && selectedBeneficiary !== undefined && (
            <View style={styles.previewBox}>
              <Text style={styles.previewText}>
                {selectedAccount.name} → {selectedBeneficiary.name}
              </Text>
            </View>
          )}

          <TouchableOpacity
            style={[styles.primaryButton, isSubmitting && styles.buttonDisabled]}
            onPress={handleReview}
            disabled={isSubmitting}
            accessibilityRole="button"
          >
            {isSubmitting ? (
              <Text style={styles.primaryButtonText}>Enviando…</Text>
            ) : (
              <Text style={styles.primaryButtonText}>Revisar transferencia</Text>
            )}
          </TouchableOpacity>
        </ScrollView>
      </KeyboardAvoidingView>
    );
  }

  // ---------------------------------------------------------------------------
  // Step 2 — Revisión
  // ---------------------------------------------------------------------------

  if (step === 'review') {
    if (isSubmitting) {
      return (
        <View style={styles.flex}>
          <LoadingState message="Confirmando transferencia…" />
        </View>
      );
    }

    const account = accounts.find((a) => a.id === pendingTransfer?.fromAccountId);
    const beneficiary = seedBeneficiaries.find(
      (b) => b.id === pendingTransfer?.beneficiaryId,
    );
    const amountFormatted = pendingTransfer
      ? `${pendingTransfer.currency} ${pendingTransfer.amount.toFixed(2)}`
      : '';

    return (
      <ScrollView style={styles.flex} contentContainerStyle={styles.scrollContent}>
        <Text style={styles.screenTitle}>Revisá tu transferencia</Text>

        <View style={styles.summaryCard}>
          <Text style={styles.summaryLabel}>Monto</Text>
          <Text style={styles.summaryValue}>{amountFormatted}</Text>

          <View style={styles.divider} />

          <Text style={styles.summaryLabel}>Desde</Text>
          <Text style={styles.summaryValue}>{account?.name ?? '—'}</Text>

          <View style={styles.divider} />

          <Text style={styles.summaryLabel}>A</Text>
          <Text style={styles.summaryValue}>{beneficiary?.name ?? '—'}</Text>
          {beneficiary !== undefined && (
            <Text style={styles.summarySubValue}>
              {beneficiary.bank} · {beneficiary.iban.slice(-8)}
            </Text>
          )}

          {pendingTransfer?.description !== '' && (
            <>
              <View style={styles.divider} />
              <Text style={styles.summaryLabel}>Descripción</Text>
              <Text style={styles.summaryValue}>{pendingTransfer?.description}</Text>
            </>
          )}
        </View>

        <TouchableOpacity
          style={styles.primaryButton}
          onPress={() => void confirmTransfer()}
          accessibilityRole="button"
        >
          <Text style={styles.primaryButtonText}>Confirmar</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.secondaryButton}
          onPress={resetTransfer}
          accessibilityRole="button"
        >
          <Text style={styles.secondaryButtonText}>Cancelar</Text>
        </TouchableOpacity>
      </ScrollView>
    );
  }

  // ---------------------------------------------------------------------------
  // Step 3 — Confirmado
  // ---------------------------------------------------------------------------

  if (step === 'confirmed') {
    const beneficiary = seedBeneficiaries.find(
      (b) => b.id === pendingTransfer?.beneficiaryId,
    );
    const amountFormatted = pendingTransfer
      ? `${pendingTransfer.currency} ${pendingTransfer.amount.toFixed(2)}`
      : '';

    return (
      <View style={styles.flex}>
        <InAppNotification
          message={notification?.message ?? ''}
          type={notification?.type ?? 'success'}
          visible={notification !== null}
          onDismiss={clearNotification}
        />

        <ScrollView
          style={styles.flex}
          contentContainerStyle={[styles.scrollContent, styles.centeredContent]}
        >
          <View style={styles.successIcon}>
            <Text style={styles.successIconText}>✓</Text>
          </View>

          <Text style={styles.successTitle}>¡Transferencia exitosa!</Text>

          <Text style={styles.successDetail}>
            Transferiste {amountFormatted}
          </Text>
          {beneficiary !== undefined && (
            <Text style={styles.successSubDetail}>a {beneficiary.name}</Text>
          )}

          <TouchableOpacity
            style={styles.primaryButton}
            onPress={resetTransfer}
            accessibilityRole="button"
          >
            <Text style={styles.primaryButtonText}>Nueva transferencia</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={() => router.push('/(app)/dashboard')}
            accessibilityRole="button"
          >
            <Text style={styles.secondaryButtonText}>Ir al dashboard</Text>
          </TouchableOpacity>
        </ScrollView>
      </View>
    );
  }

  // ---------------------------------------------------------------------------
  // Step — Error
  // ---------------------------------------------------------------------------

  return (
    <View style={styles.flex}>
      <ErrorState
        message={error ?? 'Ocurrió un error inesperado'}
        onRetry={resetTransfer}
      />
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  centeredContent: {
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
  },
  screenTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 24,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 16,
  },
  optionGroup: {
    gap: 8,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  optionItemSelected: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
  optionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  optionSubtitle: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  checkmark: {
    fontSize: 16,
    color: '#2563eb',
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: '#0f172a',
  },
  inputMultiline: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  currencyRow: {
    flexDirection: 'row',
    gap: 12,
  },
  currencyButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  currencyButtonSelected: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
  currencyText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748b',
  },
  currencyTextSelected: {
    color: '#2563eb',
  },
  errorBox: {
    backgroundColor: '#fef2f2',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
    padding: 12,
    marginTop: 16,
  },
  errorText: {
    fontSize: 14,
    color: '#dc2626',
    fontWeight: '500',
  },
  previewBox: {
    backgroundColor: '#f0fdf4',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  previewText: {
    fontSize: 14,
    color: '#166534',
    fontWeight: '500',
    textAlign: 'center',
  },
  primaryButton: {
    backgroundColor: '#2563eb',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 24,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  buttonDisabled: {
    backgroundColor: '#93c5fd',
  },
  secondaryButton: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  secondaryButtonText: {
    color: '#475569',
    fontSize: 16,
    fontWeight: '600',
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  summarySubValue: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: '#f1f5f9',
    marginVertical: 14,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#16a34a',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  successIconText: {
    fontSize: 36,
    color: '#ffffff',
    fontWeight: '700',
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
    textAlign: 'center',
  },
  successDetail: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2563eb',
    marginBottom: 4,
    textAlign: 'center',
  },
  successSubDetail: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 32,
    textAlign: 'center',
  },
});
