// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { create } from 'zustand';
import type { Account } from '@/types/index';
import { apiClient } from '@/services/api/client';
import { cacheService } from '@/services/cache/cacheService';
import { logger } from '@/utils/logger';

// ---------------------------------------------------------------------------
// State shape
// ---------------------------------------------------------------------------

interface AccountsState {
  accounts: Account[];
  isLoading: boolean;
  error: string | null;
  isOffline: boolean;
  lastFetched: number | null;

  fetchAccounts(): Promise<void>;
  getAccountById(id: string): Account | undefined;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useAccountsStore = create<AccountsState>((set, get) => ({
  accounts: [],
  isLoading: false,
  error: null,
  isOffline: false,
  lastFetched: null,

  async fetchAccounts(): Promise<void> {
    set({ isLoading: true, error: null });

    try {
      const accounts = await apiClient.get<Account[]>('/accounts');
      const cacheKey = cacheService.keys.accounts();
      await cacheService.set(cacheKey, accounts, cacheService.TTL.accounts);

      set({
        accounts,
        isLoading: false,
        isOffline: false,
        lastFetched: Date.now(),
      });
    } catch (err) {
      logger.warn('[accountsStore] Network request failed, trying cache', err);

      const cacheKey = cacheService.keys.accounts();
      const cached = await cacheService.get<Account[]>(cacheKey);

      if (cached !== null) {
        set({
          accounts: cached,
          isLoading: false,
          isOffline: true,
          error: null,
        });
      } else {
        set({
          isLoading: false,
          isOffline: true,
          error: 'No hay conexión y no hay datos cacheados',
        });
      }
    }
  },

  getAccountById(id: string): Account | undefined {
    return get().accounts.find((a) => a.id === id);
  },
}));
