// Generated by GentleIA (OpenCode) — Phase 2: Auth

import { create } from 'zustand';
import type { User } from '@/types/index';
import { authService } from '@/services/auth/authService';
import { logger } from '@/utils/logger';

// ---------------------------------------------------------------------------
// State shape
// ---------------------------------------------------------------------------

interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  isLoading: boolean;
  error: string | null;

  login(email: string, password: string): Promise<void>;
  logout(): Promise<void>;
  /**
   * Called at app startup to restore a persisted session from SecureStore.
   * Sets isAuthenticated based on whether a valid, non-expired token exists.
   */
  initialize(): Promise<void>;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useAuthStore = create<AuthState>((set) => ({
  isAuthenticated: false,
  user: null,
  isLoading: true,  // true hasta que initialize() termine — evita flash de redirección
  error: null,

  async login(email: string, password: string): Promise<void> {
    set({ isLoading: true, error: null });
    try {
      await authService.login(email, password);

      // Optionally hydrate user — best-effort; failure doesn't block login
      let user: User | null = null;
      try {
        user = await authService.getUser();
      } catch (err) {
        logger.warn('[authStore] Could not hydrate user after login', err);
      }

      set({ isAuthenticated: true, user, isLoading: false, error: null });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Login failed';
      logger.error('[authStore] Login failed', err);
      set({ isAuthenticated: false, isLoading: false, error: message });
      throw err;
    }
  },

  async logout(): Promise<void> {
    set({ isLoading: true });
    try {
      await authService.logout();
    } catch (err) {
      logger.warn('[authStore] Logout error (continuing anyway)', err);
    } finally {
      set({ isAuthenticated: false, user: null, isLoading: false, error: null });
    }
  },

  async initialize(): Promise<void> {
    set({ isLoading: true, error: null });
    try {
      const restored = await authService.restoreSession();

      if (!restored) {
        set({ isAuthenticated: false, user: null, isLoading: false });
        return;
      }

      // Hydrate user — best-effort
      let user: User | null = null;
      try {
        user = await authService.getUser();
      } catch (err) {
        logger.warn('[authStore] Could not hydrate user on initialize', err);
      }

      set({ isAuthenticated: true, user, isLoading: false });
    } catch (err) {
      logger.error('[authStore] Initialization failed', err);
      set({ isAuthenticated: false, user: null, isLoading: false });
    }
  },
}));
