// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards

import { create } from 'zustand';
import type { Card } from '@/types/index';
import { apiClient } from '@/services/api/client';
import { ApiRequestError } from '@/services/api/client';
import { logger } from '@/utils/logger';

// ---------------------------------------------------------------------------
// State shape
// ---------------------------------------------------------------------------

interface CardsState {
  cards: Card[];
  isLoading: boolean;
  error: string | null;

  fetchCards(): Promise<void>;
  toggleCardFreeze(cardId: string): Promise<void>;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useCardsStore = create<CardsState>((set, get) => ({
  cards: [],
  isLoading: false,
  error: null,

  async fetchCards(): Promise<void> {
    set({ isLoading: true, error: null });
    try {
      const cards = await apiClient.get<Card[]>('/cards');
      logger.info('[cardsStore] Cards fetched', { count: cards.length });
      set({ cards, isLoading: false });
    } catch (err) {
      const message =
        err instanceof ApiRequestError ? err.message : 'Error al cargar las tarjetas';
      logger.error('[cardsStore] fetchCards failed', err);
      set({ isLoading: false, error: message });
    }
  },

  async toggleCardFreeze(cardId: string): Promise<void> {
    const { cards } = get();
    const cardIndex = cards.findIndex((c) => c.id === cardId);
    if (cardIndex === -1) {
      logger.warn('[cardsStore] toggleCardFreeze: card not found', { cardId });
      return;
    }

    // Optimistic update — cambiar UI antes de la respuesta de red
    const originalCard = cards[cardIndex];
    const optimisticCards = cards.map((c) =>
      c.id === cardId ? { ...c, frozen: !c.frozen } : c,
    );
    set({ cards: optimisticCards });

    try {
      const updated = await apiClient.patch<Card>(`/cards/${cardId}`);
      logger.info('[cardsStore] Card freeze toggled', {
        cardId,
        frozen: updated.frozen,
      });

      // Sincronizar con respuesta real del servidor
      set((state) => ({
        cards: state.cards.map((c) => (c.id === cardId ? updated : c)),
      }));
    } catch (err) {
      // Revertir optimistic update si falla
      logger.error('[cardsStore] toggleCardFreeze failed, reverting', err);
      set((state) => ({
        cards: state.cards.map((c) => (c.id === cardId ? originalCard : c)),
      }));
    }
  },
}));
