// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { create } from 'zustand';
import type { Transaction, PaginationMeta, PaginatedResponse } from '@/types/index';
import { apiClient } from '@/services/api/client';
import { cacheService } from '@/services/cache/cacheService';
import { logger } from '@/utils/logger';

// ---------------------------------------------------------------------------
// State shape
// ---------------------------------------------------------------------------

interface TransactionsState {
  transactionsByAccount: Record<string, Transaction[]>;
  paginationByAccount: Record<string, PaginationMeta>;
  loadingByAccount: Record<string, boolean>;
  errorByAccount: Record<string, string | null>;

  fetchTransactions(accountId: string, page?: number): Promise<void>;
  loadMoreTransactions(accountId: string): Promise<void>;
  getTransactions(accountId: string): Transaction[];
  getPagination(accountId: string): PaginationMeta | null;
  isLoading(accountId: string): boolean;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useTransactionsStore = create<TransactionsState>((set, get) => ({
  transactionsByAccount: {},
  paginationByAccount: {},
  loadingByAccount: {},
  errorByAccount: {},

  async fetchTransactions(accountId: string, page = 1): Promise<void> {
    set((state) => ({
      loadingByAccount: { ...state.loadingByAccount, [accountId]: true },
      errorByAccount: { ...state.errorByAccount, [accountId]: null },
    }));

    try {
      const response = await apiClient.get<PaginatedResponse<Transaction>>(
        `/accounts/${accountId}/transactions?page=${page}&limit=20`,
      );

      // Persist to cache
      const cacheKey = cacheService.keys.transactions(accountId, page);
      await cacheService.set(cacheKey, response, cacheService.TTL.transactions);

      set((state) => {
        const existing = state.transactionsByAccount[accountId] ?? [];
        const updated = page === 1 ? response.data : [...existing, ...response.data];

        return {
          transactionsByAccount: { ...state.transactionsByAccount, [accountId]: updated },
          paginationByAccount: { ...state.paginationByAccount, [accountId]: response.pagination },
          loadingByAccount: { ...state.loadingByAccount, [accountId]: false },
        };
      });
    } catch (err) {
      logger.warn('[transactionsStore] Network request failed, trying cache', err);

      const cacheKey = cacheService.keys.transactions(accountId, page);
      const cached = await cacheService.get<PaginatedResponse<Transaction>>(cacheKey);

      if (cached !== null) {
        set((state) => {
          const existing = state.transactionsByAccount[accountId] ?? [];
          const updated = page === 1 ? cached.data : [...existing, ...cached.data];

          return {
            transactionsByAccount: { ...state.transactionsByAccount, [accountId]: updated },
            paginationByAccount: {
              ...state.paginationByAccount,
              [accountId]: cached.pagination,
            },
            loadingByAccount: { ...state.loadingByAccount, [accountId]: false },
          };
        });
      } else {
        const message =
          err instanceof Error ? err.message : 'Error al cargar transacciones';
        set((state) => ({
          loadingByAccount: { ...state.loadingByAccount, [accountId]: false },
          errorByAccount: { ...state.errorByAccount, [accountId]: message },
        }));
      }
    }
  },

  async loadMoreTransactions(accountId: string): Promise<void> {
    const pagination = get().paginationByAccount[accountId];
    if (!pagination?.hasNextPage) return;
    if (get().loadingByAccount[accountId]) return;

    await get().fetchTransactions(accountId, pagination.page + 1);
  },

  getTransactions(accountId: string): Transaction[] {
    return get().transactionsByAccount[accountId] ?? [];
  },

  getPagination(accountId: string): PaginationMeta | null {
    return get().paginationByAccount[accountId] ?? null;
  },

  isLoading(accountId: string): boolean {
    return get().loadingByAccount[accountId] ?? false;
  },
}));
