// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards

import { create } from 'zustand';
import type { Transfer } from '@/types/index';
import { apiClient } from '@/services/api/client';
import { ApiRequestError } from '@/services/api/client';
import { useAccountsStore } from './accountsStore';
import { logger } from '@/utils/logger';

// ---------------------------------------------------------------------------
// State shape
// ---------------------------------------------------------------------------

type TransferStep = 'form' | 'review' | 'confirmed' | 'error';
type Currency = 'PEN' | 'USD';

interface Notification {
  message: string;
  type: 'success' | 'error';
}

interface TransferState {
  // Flujo en 3 pasos
  step: TransferStep;

  // Datos del formulario
  fromAccountId: string | null;
  beneficiaryId: string | null;
  amount: string;
  currency: Currency;
  description: string;

  // Transfer pendiente (después del POST /transfers)
  pendingTransfer: Transfer | null;

  // Estado de carga
  isSubmitting: boolean;
  error: string | null;

  // Notificación in-app
  notification: Notification | null;

  // Actions
  setFormData(
    data: Partial<{
      fromAccountId: string | null;
      beneficiaryId: string | null;
      amount: string;
      currency: Currency;
      description: string;
    }>,
  ): void;

  validate(): string | null;
  submitTransfer(): Promise<void>;
  confirmTransfer(): Promise<void>;
  resetTransfer(): void;
  clearNotification(): void;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useTransferStore = create<TransferState>((set, get) => ({
  step: 'form',
  fromAccountId: null,
  beneficiaryId: null,
  amount: '',
  currency: 'PEN',
  description: '',
  pendingTransfer: null,
  isSubmitting: false,
  error: null,
  notification: null,

  setFormData(data) {
    set((state) => ({ ...state, ...data }));
  },

  validate(): string | null {
    const { fromAccountId, beneficiaryId, amount } = get();

    if (fromAccountId === null) {
      return 'Seleccioná una cuenta de origen';
    }

    if (beneficiaryId === null) {
      return 'Seleccioná un beneficiario';
    }

    const parsed = parseFloat(amount);
    if (isNaN(parsed) || parsed <= 0) {
      return 'El monto debe ser mayor a 0';
    }

    // Verificar saldo disponible en la cuenta origen
    const account = useAccountsStore.getState().getAccountById(fromAccountId);
    if (account !== undefined && parsed > account.balance) {
      return `Saldo insuficiente. Disponible: ${account.currency} ${account.balance.toFixed(2)}`;
    }

    return null;
  },

  async submitTransfer(): Promise<void> {
    const validationError = get().validate();
    if (validationError !== null) {
      set({ error: validationError });
      return;
    }

    const { fromAccountId, beneficiaryId, amount, currency, description } = get();

    set({ isSubmitting: true, error: null });

    try {
      const transfer = await apiClient.post<Transfer>('/transfers', {
        fromAccountId,
        beneficiaryId,
        amount: parseFloat(amount),
        currency,
        description,
      });

      logger.info('[transferStore] Transfer submitted', { transferId: transfer.id });
      set({ pendingTransfer: transfer, isSubmitting: false, step: 'review' });
    } catch (err) {
      const message =
        err instanceof ApiRequestError
          ? err.message
          : 'Error al enviar la transferencia';
      logger.error('[transferStore] submitTransfer failed', err);
      set({ isSubmitting: false, error: message, step: 'error' });
    }
  },

  async confirmTransfer(): Promise<void> {
    const { pendingTransfer } = get();
    if (pendingTransfer === null) {
      set({ error: 'No hay transferencia pendiente de confirmar', step: 'error' });
      return;
    }

    set({ isSubmitting: true, error: null });

    try {
      const confirmed = await apiClient.post<Transfer>(
        `/transfers/${pendingTransfer.id}/confirm`,
      );

      logger.info('[transferStore] Transfer confirmed', { transferId: confirmed.id });
      set({
        pendingTransfer: confirmed,
        isSubmitting: false,
        step: 'confirmed',
        notification: {
          message: '¡Transferencia realizada con éxito!',
          type: 'success',
        },
      });
    } catch (err) {
      const message =
        err instanceof ApiRequestError
          ? err.message
          : 'Error al confirmar la transferencia';
      logger.error('[transferStore] confirmTransfer failed', err);
      set({ isSubmitting: false, error: message, step: 'error' });
    }
  },

  resetTransfer(): void {
    set({
      step: 'form',
      fromAccountId: null,
      beneficiaryId: null,
      amount: '',
      currency: 'PEN',
      description: '',
      pendingTransfer: null,
      isSubmitting: false,
      error: null,
      notification: null,
    });
  },

  clearNotification(): void {
    set({ notification: null });
  },
}));
