// Generated by GentleIA (OpenCode) — Phase 2: Auth

import { useEffect } from 'react';
import { Stack, useRouter, useSegments } from 'expo-router';
import { useAuthStore } from '@/stores/authStore';
import { setupMockServer } from '@/services/api/setup';

// ---------------------------------------------------------------------------
// MSW bootstrap — only in test environment, once per process
// ---------------------------------------------------------------------------

if (typeof process !== 'undefined' && process.env['NODE_ENV'] === 'test') {
  setupMockServer();
}

// ---------------------------------------------------------------------------
// Auth redirect guard
// ---------------------------------------------------------------------------

function AuthGuard() {
  const { isAuthenticated, isLoading, initialize } = useAuthStore();
  const router = useRouter();
  const segments = useSegments();

  // Restore session from SecureStore on first render
  useEffect(() => {
    initialize();
    // initialize is stable (zustand action refs don't change)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (isLoading) return;

    const inAuthGroup = segments[0] === '(auth)';

    if (!isAuthenticated && !inAuthGroup) {
      router.replace('/(auth)/login');
    } else if (isAuthenticated && inAuthGroup) {
      router.replace('/(app)/dashboard');
    }
  }, [isAuthenticated, isLoading, segments, router]);

  return null;
}

// ---------------------------------------------------------------------------
// Root layout
// ---------------------------------------------------------------------------

export default function RootLayout() {
  return (
    <>
      <AuthGuard />
      <Stack screenOptions={{ headerShown: false }} />
    </>
  );
}
