// Generated by GentleIA (OpenCode) — Phase 1: Mock API

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

export interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

export type AccountType = 'checking' | 'savings' | 'investment';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  balance: number;
  currency: string;
  /** Last 4 digits of the IBAN — full number is never exposed to the client */
  iban: string;
}

export type TransactionType = 'credit' | 'debit';

export interface Transaction {
  id: string;
  accountId: string;
  amount: number;
  type: TransactionType;
  description: string;
  category: string;
  /** ISO-8601 date-time string */
  date: string;
  /** Account balance after this transaction */
  balance: number;
}

export type CardBrand = 'visa' | 'mastercard';

export interface Card {
  id: string;
  accountId: string;
  lastFour: string;
  brand: CardBrand;
  frozen: boolean;
  expiresAt: string;
}

export interface Beneficiary {
  id: string;
  name: string;
  iban: string;
  bank: string;
}

export type TransferStatus = 'pending' | 'confirmed' | 'failed';

export interface Transfer {
  id: string;
  fromAccountId: string;
  toAccountId?: string;
  beneficiaryId?: string;
  amount: number;
  currency: string;
  description: string;
  status: TransferStatus;
  createdAt: string;
}

export interface TransferRequest {
  fromAccountId: string;
  beneficiaryId: string;
  amount: number;
  currency: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Pagination
// ---------------------------------------------------------------------------

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNextPage: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: PaginationMeta;
}

// ---------------------------------------------------------------------------
// API primitives
// ---------------------------------------------------------------------------

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type: 'Bearer';
  expires_in: number;
}
