// Generated by GentleIA (OpenCode) — Phase 1: Mock API

import type { ApiError } from '@/types/index';
import { tokenStore } from '../auth/tokenStore';
import { devApiClient } from './devClient';

// ---------------------------------------------------------------------------
// Typed error
// ---------------------------------------------------------------------------

export class ApiRequestError extends Error {
  readonly code: string;
  readonly details?: Record<string, unknown>;
  readonly httpStatus: number;

  constructor(apiError: ApiError, httpStatus: number) {
    super(apiError.message);
    this.name = 'ApiRequestError';
    this.code = apiError.code;
    this.details = apiError.details;
    this.httpStatus = httpStatus;
  }
}

// ---------------------------------------------------------------------------
// Base URL — reads from Expo env var, falls back to localhost for tests
// ---------------------------------------------------------------------------

const BASE_URL =
  (typeof process !== 'undefined' && process.env['EXPO_PUBLIC_API_BASE_URL']) || '';

// ---------------------------------------------------------------------------
// Core request helper
// ---------------------------------------------------------------------------

type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

async function request<T>(
  method: HttpMethod,
  path: string,
  body?: unknown,
): Promise<T> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };

  const token = tokenStore.getAccessToken();
  if (token !== null) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const init: RequestInit = {
    method,
    headers,
  };

  if (body !== undefined) {
    init.body = JSON.stringify(body);
  }

  const response = await fetch(`${BASE_URL}${path}`, init);

  if (!response.ok) {
    let apiError: ApiError;
    try {
      apiError = (await response.json()) as ApiError;
    } catch {
      apiError = {
        code: 'UNKNOWN_ERROR',
        message: `HTTP ${response.status} — ${response.statusText}`,
      };
    }
    throw new ApiRequestError(apiError, response.status);
  }

  // Handle 204 No Content
  if (response.status === 204) {
    return undefined as T;
  }

  return response.json() as Promise<T>;
}

// ---------------------------------------------------------------------------
// HTTP-based client (usado en tests con MSW interceptando fetch)
// ---------------------------------------------------------------------------

export const httpApiClient = {
  get<T>(path: string): Promise<T> {
    return request<T>('GET', path);
  },

  post<T>(path: string, body?: unknown): Promise<T> {
    return request<T>('POST', path, body);
  },

  patch<T>(path: string, body?: unknown): Promise<T> {
    return request<T>('PATCH', path, body);
  },

  put<T>(path: string, body?: unknown): Promise<T> {
    return request<T>('PUT', path, body);
  },

  delete<T>(path: string): Promise<T> {
    return request<T>('DELETE', path);
  },
};

// ---------------------------------------------------------------------------
// Public apiClient — en __DEV__ (Expo Go) usa devClient sin fetch;
// en tests usa el cliente HTTP real que MSW intercepta.
// ---------------------------------------------------------------------------

export const apiClient =
  typeof __DEV__ !== 'undefined' && __DEV__ && process.env['NODE_ENV'] !== 'test'
    ? devApiClient
    : httpApiClient;
