// Generated by GentleIA (OpenCode) — Phase 1: Mock API

import { http, HttpResponse, delay } from 'msw';
import type {
  TokenResponse,
  Transfer,
  TransferRequest,
} from '@/types/index';
import {
  seedUser,
  seedAccounts,
  seedTransactions,
  seedCards,
  seedBeneficiaries,
} from './seed';

// ---------------------------------------------------------------------------
// In-memory mutable state (resets when the MSW server restarts)
// ---------------------------------------------------------------------------

const transferStore = new Map<string, Transfer>();
let cardStore = seedCards.map((c) => ({ ...c }));
let transferCounter = 1;

// ---------------------------------------------------------------------------
// Auth helpers
// ---------------------------------------------------------------------------

const MOCK_ACCESS_TOKEN = 'mock-access-token-abc123';
const MOCK_REFRESH_TOKEN = 'mock-refresh-token-xyz789';

function requireAuth(request: Request): boolean {
  const auth = request.headers.get('Authorization');
  return auth === `Bearer ${MOCK_ACCESS_TOKEN}`;
}

function unauthorized(): HttpResponse<{ code: string; message: string }> {
  return HttpResponse.json(
    { code: 'UNAUTHORIZED', message: 'Missing or invalid authorization token' },
    { status: 401 },
  );
}

// ---------------------------------------------------------------------------
// Latency helpers (realistic feel without slowing down tests too much)
// ---------------------------------------------------------------------------

const FAST = (): Promise<void> => delay(200 + Math.random() * 200);
const MEDIUM = (): Promise<void> => delay(600);
const SLOW = (): Promise<void> => delay(1200);

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

export const handlers = [
  // ---------- POST /auth/token ------------------------------------------------
  http.post('/auth/token', async () => {
    await FAST();
    const body: TokenResponse = {
      access_token: MOCK_ACCESS_TOKEN,
      refresh_token: MOCK_REFRESH_TOKEN,
      token_type: 'Bearer',
      expires_in: 3600,
    };
    // Never log access_token — only confirm exchange happened
    console.debug('[MSW] auth/token: exchange successful, tokens=[REDACTED]');
    return HttpResponse.json(body, { status: 200 });
  }),

  // ---------- GET /auth/me ---------------------------------------------------
  http.get('/auth/me', async ({ request }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();
    return HttpResponse.json(seedUser, { status: 200 });
  }),

  // ---------- GET /accounts --------------------------------------------------
  http.get('/accounts', async ({ request }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();
    return HttpResponse.json(seedAccounts, { status: 200 });
  }),

  // ---------- GET /accounts/:id ----------------------------------------------
  http.get('/accounts/:id', async ({ request, params }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();

    const account = seedAccounts.find((a) => a.id === params.id);
    if (!account) {
      return HttpResponse.json(
        { code: 'NOT_FOUND', message: `Account ${params.id} not found` },
        { status: 404 },
      );
    }
    return HttpResponse.json(account, { status: 200 });
  }),

  // ---------- GET /accounts/:id/transactions ---------------------------------
  http.get('/accounts/:id/transactions', async ({ request, params }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();

    const url = new URL(request.url);
    const page = Math.max(1, parseInt(url.searchParams.get('page') ?? '1', 10));
    const limit = Math.min(
      100,
      Math.max(1, parseInt(url.searchParams.get('limit') ?? '20', 10)),
    );

    const allTx = seedTransactions
      .filter((t) => t.accountId === params.id)
      // Most recent first
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    const total = allTx.length;
    const totalPages = Math.ceil(total / limit);
    const start = (page - 1) * limit;
    const data = allTx.slice(start, start + limit);

    return HttpResponse.json(
      {
        data,
        pagination: {
          page,
          limit,
          total,
          totalPages,
          hasNextPage: page < totalPages,
        },
      },
      { status: 200 },
    );
  }),

  // ---------- POST /transfers ------------------------------------------------
  http.post('/transfers', async ({ request }) => {
    await MEDIUM();
    if (!requireAuth(request)) return unauthorized();

    const body = (await request.json()) as TransferRequest;

    // Basic validation
    if (!body.fromAccountId || !body.beneficiaryId || !body.amount || body.amount <= 0) {
      return HttpResponse.json(
        { code: 'VALIDATION_ERROR', message: 'Missing or invalid transfer fields' },
        { status: 422 },
      );
    }

    const fromAccount = seedAccounts.find((a) => a.id === body.fromAccountId);
    if (!fromAccount) {
      return HttpResponse.json(
        { code: 'NOT_FOUND', message: `Account ${body.fromAccountId} not found` },
        { status: 404 },
      );
    }

    const beneficiary = seedBeneficiaries.find((b) => b.id === body.beneficiaryId);
    if (!beneficiary) {
      return HttpResponse.json(
        { code: 'NOT_FOUND', message: `Beneficiary ${body.beneficiaryId} not found` },
        { status: 404 },
      );
    }

    const transfer: Transfer = {
      id: `tr-${String(transferCounter++).padStart(4, '0')}`,
      fromAccountId: body.fromAccountId,
      beneficiaryId: body.beneficiaryId,
      amount: body.amount,
      currency: body.currency ?? fromAccount.currency,
      description: body.description ?? '',
      status: 'pending',
      createdAt: new Date().toISOString(),
    };

    transferStore.set(transfer.id, transfer);
    return HttpResponse.json(transfer, { status: 201 });
  }),

  // ---------- POST /transfers/:id/confirm ------------------------------------
  http.post('/transfers/:id/confirm', async ({ request, params }) => {
    await SLOW();
    if (!requireAuth(request)) return unauthorized();

    const transfer = transferStore.get(params.id as string);
    if (!transfer) {
      return HttpResponse.json(
        { code: 'NOT_FOUND', message: `Transfer ${params.id} not found` },
        { status: 404 },
      );
    }

    if (transfer.status !== 'pending') {
      return HttpResponse.json(
        {
          code: 'INVALID_STATE',
          message: `Transfer is already ${transfer.status} and cannot be confirmed`,
        },
        { status: 409 },
      );
    }

    const confirmed: Transfer = { ...transfer, status: 'confirmed' };
    transferStore.set(confirmed.id, confirmed);
    return HttpResponse.json(confirmed, { status: 200 });
  }),

  // ---------- GET /cards -----------------------------------------------------
  http.get('/cards', async ({ request }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();
    return HttpResponse.json(cardStore, { status: 200 });
  }),

  // ---------- PATCH /cards/:id -----------------------------------------------
  http.patch('/cards/:id', async ({ request, params }) => {
    await FAST();
    if (!requireAuth(request)) return unauthorized();

    const idx = cardStore.findIndex((c) => c.id === params.id);
    if (idx === -1) {
      return HttpResponse.json(
        { code: 'NOT_FOUND', message: `Card ${params.id} not found` },
        { status: 404 },
      );
    }

    // Toggle frozen field regardless of what the body says — simpler UX
    cardStore = cardStore.map((c, i) =>
      i === idx ? { ...c, frozen: !c.frozen } : c,
    );

    return HttpResponse.json(cardStore[idx], { status: 200 });
  }),
];
