// Generated by GentleIA (OpenCode) — Phase 1: Mock API

import type {
  User,
  Account,
  Transaction,
  Card,
  Beneficiary,
} from '@/types/index';

// ---------------------------------------------------------------------------
// User
// ---------------------------------------------------------------------------

export const seedUser: User = {
  id: 'user-1',
  name: 'María García',
  email: 'maria.garcia@example.com',
};

// ---------------------------------------------------------------------------
// Accounts  (currency: PEN — Soles peruanos, Inteligo Group)
// ---------------------------------------------------------------------------

export const seedAccounts: Account[] = [
  {
    id: 'acc-001',
    name: 'Cuenta Corriente',
    type: 'checking',
    balance: 15_480.5,
    currency: 'PEN',
    iban: '3271',
  },
  {
    id: 'acc-002',
    name: 'Cuenta de Ahorros',
    type: 'savings',
    balance: 45_220.0,
    currency: 'PEN',
    iban: '8844',
  },
  {
    id: 'acc-003',
    name: 'Cartera de Inversiones',
    type: 'investment',
    balance: 120_750.0,
    currency: 'PEN',
    iban: '5519',
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function iso(date: Date): string {
  return date.toISOString();
}

function daysAgo(n: number): Date {
  const d = new Date('2026-04-30T12:00:00Z');
  d.setDate(d.getDate() - n);
  return d;
}

// ---------------------------------------------------------------------------
// Transactions — 25 per account, realistic Peruvian context
// ---------------------------------------------------------------------------

const checkingTx: Omit<Transaction, 'id' | 'accountId'>[] = [
  { amount: 8_500,    type: 'credit',  description: 'Depósito de nómina — Inteligo SAB',       category: 'salary',        date: iso(daysAgo(1)),  balance: 15_480.5 },
  { amount: 245.9,    type: 'debit',   description: 'Wong Surco — compras supermercado',        category: 'groceries',     date: iso(daysAgo(2)),  balance: 6_980.5 },
  { amount: 120,      type: 'debit',   description: 'Movistar — servicio de internet',          category: 'utilities',     date: iso(daysAgo(3)),  balance: 7_226.4 },
  { amount: 85,       type: 'debit',   description: 'Uber Eats — delivery cena',                category: 'food',          date: iso(daysAgo(4)),  balance: 7_346.4 },
  { amount: 350,      type: 'debit',   description: 'Cinépolis Miraflores — cine y snacks',     category: 'entertainment', date: iso(daysAgo(5)),  balance: 7_431.4 },
  { amount: 2_000,    type: 'debit',   description: 'Transferencia a ahorros',                  category: 'transfer',      date: iso(daysAgo(6)),  balance: 7_781.4 },
  { amount: 55.5,     type: 'debit',   description: 'Rappi — delivery almuerzo',                category: 'food',          date: iso(daysAgo(7)),  balance: 9_781.4 },
  { amount: 410,      type: 'debit',   description: 'Plaza Vea San Isidro — supermercado',      category: 'groceries',     date: iso(daysAgo(8)),  balance: 9_836.9 },
  { amount: 650,      type: 'debit',   description: 'Clínica Ricardo Palma — consulta médica',  category: 'health',        date: iso(daysAgo(9)),  balance: 10_246.9 },
  { amount: 8_500,    type: 'credit',  description: 'Depósito de nómina — Inteligo SAB',        category: 'salary',        date: iso(daysAgo(16)), balance: 10_896.9 },
  { amount: 90,       type: 'debit',   description: 'Taxi Beat — traslados semana',             category: 'transport',     date: iso(daysAgo(17)), balance: 2_396.9 },
  { amount: 180,      type: 'debit',   description: 'La Italiana — cena con familia',           category: 'food',          date: iso(daysAgo(18)), balance: 2_486.9 },
  { amount: 220,      type: 'debit',   description: 'Farmacia Inkafarma — medicamentos',        category: 'health',        date: iso(daysAgo(19)), balance: 2_666.9 },
  { amount: 1_200,    type: 'debit',   description: 'Alquiler cochera — Miraflores',            category: 'housing',       date: iso(daysAgo(20)), balance: 2_886.9 },
  { amount: 75,       type: 'debit',   description: 'Netflix + Spotify — suscripciones',        category: 'entertainment', date: iso(daysAgo(21)), balance: 4_086.9 },
  { amount: 300,      type: 'credit',  description: 'Transferencia recibida — Carlos Quispe',   category: 'transfer',      date: iso(daysAgo(22)), balance: 4_161.9 },
  { amount: 95,       type: 'debit',   description: 'Wong San Borja — supermercado',            category: 'groceries',     date: iso(daysAgo(23)), balance: 3_861.9 },
  { amount: 40,       type: 'debit',   description: 'Starbucks San Isidro — café',              category: 'food',          date: iso(daysAgo(24)), balance: 3_956.9 },
  { amount: 8_500,    type: 'credit',  description: 'Depósito de nómina — Inteligo SAB',        category: 'salary',        date: iso(daysAgo(31)), balance: 3_996.9 },
  { amount: 560,      type: 'debit',   description: 'Tottus Surco — supermercado quincenal',    category: 'groceries',     date: iso(daysAgo(32)), balance: -4_503.1 },
  { amount: 200,      type: 'debit',   description: 'Gasolina Primax — combustible',            category: 'transport',     date: iso(daysAgo(33)), balance: -3_943.1 },
  { amount: 130,      type: 'debit',   description: 'Luz del Sur — recibo de luz',              category: 'utilities',     date: iso(daysAgo(34)), balance: -3_743.1 },
  { amount: 88,       type: 'debit',   description: 'Sedapal — recibo de agua',                 category: 'utilities',     date: iso(daysAgo(35)), balance: -3_613.1 },
  { amount: 500,      type: 'credit',  description: 'Cashback tarjeta de crédito',              category: 'reward',        date: iso(daysAgo(36)), balance: -3_525.1 },
  { amount: 3_000,    type: 'debit',   description: 'Pago tarjeta de crédito BCP',              category: 'credit_card',   date: iso(daysAgo(37)), balance: -4_025.1 },
];

const savingsTx: Omit<Transaction, 'id' | 'accountId'>[] = [
  { amount: 2_000,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(6)),  balance: 45_220.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(36)), balance: 43_220.0 },
  { amount: 850,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(30)), balance: 41_720.0 },
  { amount: 5_000,    type: 'debit',   description: 'Adelanto a inversiones',                  category: 'transfer',      date: iso(daysAgo(45)), balance: 40_870.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(66)), balance: 45_870.0 },
  { amount: 830,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(60)), balance: 44_370.0 },
  { amount: 2_500,    type: 'debit',   description: 'Pago inicial depa — Inmobiliaria Lima',   category: 'housing',       date: iso(daysAgo(75)), balance: 43_540.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(96)), balance: 46_040.0 },
  { amount: 810,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(90)), balance: 44_540.0 },
  { amount: 10_000,   type: 'credit',  description: 'Depósito inicial apertura de cuenta',     category: 'deposit',       date: iso(daysAgo(180)), balance: 43_730.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(126)), balance: 33_730.0 },
  { amount: 790,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(120)), balance: 32_230.0 },
  { amount: 3_000,    type: 'debit',   description: 'Retiro para emergencia familiar',         category: 'withdrawal',    date: iso(daysAgo(135)), balance: 31_440.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(156)), balance: 34_440.0 },
  { amount: 770,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(150)), balance: 32_940.0 },
  { amount: 5_000,    type: 'credit',  description: 'Bono anual — Inteligo SAB',               category: 'salary',        date: iso(daysAgo(160)), balance: 32_170.0 },
  { amount: 2_000,    type: 'debit',   description: 'Seguro de vida — Rimac Seguros',          category: 'insurance',     date: iso(daysAgo(165)), balance: 27_170.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(186)), balance: 29_170.0 },
  { amount: 750,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(180)), balance: 27_670.0 },
  { amount: 4_000,    type: 'debit',   description: 'Viaje a Cusco — gastos de vacaciones',    category: 'travel',        date: iso(daysAgo(190)), balance: 26_920.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(216)), balance: 30_920.0 },
  { amount: 730,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(210)), balance: 29_420.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(246)), balance: 28_690.0 },
  { amount: 710,      type: 'credit',  description: 'Intereses mensuales — tasa 4.2% TEA',     category: 'interest',      date: iso(daysAgo(240)), balance: 27_190.0 },
  { amount: 1_500,    type: 'credit',  description: 'Transferencia desde corriente',            category: 'transfer',      date: iso(daysAgo(270)), balance: 26_480.0 },
];

const investmentTx: Omit<Transaction, 'id' | 'accountId'>[] = [
  { amount: 5_000,    type: 'credit',  description: 'Transferencia desde ahorros',              category: 'transfer',      date: iso(daysAgo(45)),  balance: 120_750.0 },
  { amount: 3_200,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(30)),  balance: 115_750.0 },
  { amount: 2_100,    type: 'debit',   description: 'Rescate parcial fondo — liquidez',         category: 'withdrawal',    date: iso(daysAgo(50)),  balance: 112_550.0 },
  { amount: 3_100,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(60)),  balance: 114_650.0 },
  { amount: 10_000,   type: 'credit',  description: 'Inversión adicional — bono recibido',      category: 'deposit',       date: iso(daysAgo(70)),  balance: 111_550.0 },
  { amount: 3_000,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(90)),  balance: 101_550.0 },
  { amount: 2_900,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(120)), balance: 98_550.0 },
  { amount: 5_000,    type: 'debit',   description: 'Rescate parcial — pago cuota depa',        category: 'withdrawal',    date: iso(daysAgo(130)), balance: 95_650.0 },
  { amount: 2_800,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(150)), balance: 100_650.0 },
  { amount: 15_000,   type: 'credit',  description: 'Depósito — portfolio rebalanceo',          category: 'deposit',       date: iso(daysAgo(160)), balance: 97_850.0 },
  { amount: 2_700,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(180)), balance: 82_850.0 },
  { amount: 2_600,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(210)), balance: 80_150.0 },
  { amount: 3_000,    type: 'debit',   description: 'Rescate — gastos excepcionales',            category: 'withdrawal',    date: iso(daysAgo(220)), balance: 77_550.0 },
  { amount: 2_500,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(240)), balance: 80_550.0 },
  { amount: 20_000,   type: 'credit',  description: 'Depósito inicial — apertura cartera',      category: 'deposit',       date: iso(daysAgo(365)), balance: 78_050.0 },
  { amount: 2_400,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(270)), balance: 58_050.0 },
  { amount: 2_300,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(300)), balance: 55_650.0 },
  { amount: 2_200,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(330)), balance: 53_350.0 },
  { amount: 10_000,   type: 'credit',  description: 'Suscripción adicional fondo Sura',         category: 'deposit',       date: iso(daysAgo(340)), balance: 51_150.0 },
  { amount: 2_100,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(360)), balance: 41_150.0 },
  { amount: 1_000,    type: 'debit',   description: 'Comisión anual — Sura Inversiones',        category: 'fee',           date: iso(daysAgo(362)), balance: 39_050.0 },
  { amount: 2_000,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(390)), balance: 40_050.0 },
  { amount: 1_900,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(420)), balance: 38_050.0 },
  { amount: 5_000,    type: 'credit',  description: 'Suscripción adicional fondo Sura',         category: 'deposit',       date: iso(daysAgo(430)), balance: 36_150.0 },
  { amount: 1_800,    type: 'credit',  description: 'Rendimiento fondo mutuo — Sura FMM',       category: 'interest',      date: iso(daysAgo(450)), balance: 31_150.0 },
];

function buildTransactions(
  accountId: string,
  items: Omit<Transaction, 'id' | 'accountId'>[],
): Transaction[] {
  return items.map((item, i) => ({
    id: `tx-${accountId}-${String(i + 1).padStart(3, '0')}`,
    accountId,
    ...item,
  }));
}

export const seedTransactions: Transaction[] = [
  ...buildTransactions('acc-001', checkingTx),
  ...buildTransactions('acc-002', savingsTx),
  ...buildTransactions('acc-003', investmentTx),
];

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

export const seedCards: Card[] = [
  {
    id: 'card-001',
    accountId: 'acc-001',
    lastFour: '4821',
    brand: 'visa',
    frozen: false,
    expiresAt: '2028-06',
  },
  {
    id: 'card-002',
    accountId: 'acc-002',
    lastFour: '3374',
    brand: 'mastercard',
    frozen: false,
    expiresAt: '2027-11',
  },
];

// ---------------------------------------------------------------------------
// Beneficiaries — fictitious Peruvian names and IBANs
// ---------------------------------------------------------------------------

export const seedBeneficiaries: Beneficiary[] = [
  {
    id: 'ben-001',
    name: 'Carlos Quispe Mamani',
    iban: 'PE00 0011 2233 4455 6677 8800',
    bank: 'BCP',
  },
  {
    id: 'ben-002',
    name: 'Lucía Fernández Torres',
    iban: 'PE00 0022 3344 5566 7788 9911',
    bank: 'Interbank',
  },
  {
    id: 'ben-003',
    name: 'Diego Salazar Vargas',
    iban: 'PE00 0033 4455 6677 8899 0022',
    bank: 'BBVA',
  },
];
