// Generated by GentleIA (OpenCode) — Phase 1: Mock API

/**
 * MSW setup for React Native / Expo.
 *
 * React Native does NOT use Service Workers (browser API).
 * For RN we rely on msw/native (fetch interceptor via react-native-fetch-api polyfill)
 * or msw/node for unit/integration tests run in a Node environment.
 *
 * Strategy:
 *  - In Jest (NODE environment): use setupServer from msw/node
 *  - In the live Expo app (DEV only): start the same server using undici fetch polyfill
 *
 * Call `setupMockServer()` once at app bootstrap (e.g., App.tsx or jest setupFiles).
 */

import { handlers } from './handlers';

// ---------------------------------------------------------------------------
// Node / Jest environment (used by tests)
// ---------------------------------------------------------------------------

let _server: ReturnType<typeof import('msw/node').setupServer> | null = null;

export function setupMockServer() {
  if (typeof process !== 'undefined' && process.env['NODE_ENV'] === 'test') {
    // Lazy import so it doesn't blow up on non-node environments
    const { setupServer } = require('msw/node') as typeof import('msw/node');
    _server = setupServer(...handlers);
    _server.listen({ onUnhandledRequest: 'warn' });
    console.debug('[MSW] mock server started in NODE/test mode');
    return _server;
  }

  /**
   * In Expo development (non-test), MSW for React Native uses a fetch polyfill.
   * This requires the `msw` package AND the app's metro config to be aware of it.
   *
   * For now we log a warning if someone accidentally calls this outside of tests.
   * A full RN integration would use `msw/native` or `@mswjs/interceptors`.
   */
  if (__DEV__) {
    console.warn(
      '[MSW] setupMockServer() called in non-test environment. ' +
        'For live dev mocks in React Native, configure msw/native separately.',
    );
  }

  return null;
}

/**
 * Tear down the server after all tests.
 * Call this in Jest's `afterAll` hook.
 */
export function teardownMockServer() {
  if (_server) {
    _server.close();
    _server = null;
    console.debug('[MSW] mock server closed');
  }
}

/**
 * Reset request handlers between tests so side-effects don't bleed.
 * Call this in Jest's `afterEach` hook.
 */
export function resetMockHandlers() {
  if (_server) {
    _server.resetHandlers();
  }
}

/**
 * Convenience export for test files that want direct access.
 * Usage:
 *   import { mockServer } from '@/services/api/setup';
 *   mockServer.use(http.get('/accounts', () => HttpResponse.json([])));
 */
export function getMockServer() {
  return _server;
}
