// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import AsyncStorage from '@react-native-async-storage/async-storage';

// ---------------------------------------------------------------------------
// TTL constants
// ---------------------------------------------------------------------------

const TTL_ACCOUNTS_MS = 5 * 60 * 1000; // 5 minutes
const TTL_TRANSACTIONS_MS = 2 * 60 * 1000; // 2 minutes

// ---------------------------------------------------------------------------
// Cache entry shape
// ---------------------------------------------------------------------------

interface CacheEntry<T> {
  data: T;
  cachedAt: number;
  expiresAt: number;
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

export const cacheService = {
  async set<T>(key: string, data: T, ttlMs?: number): Promise<void> {
    const now = Date.now();
    const entry: CacheEntry<T> = {
      data,
      cachedAt: now,
      expiresAt: now + (ttlMs ?? TTL_ACCOUNTS_MS),
    };
    await AsyncStorage.setItem(key, JSON.stringify(entry));
  },

  async get<T>(key: string): Promise<T | null> {
    const raw = await AsyncStorage.getItem(key);
    if (raw === null) return null;

    let entry: CacheEntry<T>;
    try {
      entry = JSON.parse(raw) as CacheEntry<T>;
    } catch {
      return null;
    }

    if (Date.now() > entry.expiresAt) {
      await AsyncStorage.removeItem(key);
      return null;
    }

    return entry.data;
  },

  async remove(key: string): Promise<void> {
    await AsyncStorage.removeItem(key);
  },

  keys: {
    accounts: (): string => 'bankgo:accounts',
    transactions: (accountId: string, page: number): string =>
      `bankgo:transactions:${accountId}:${page}`,
  },

  // Expose TTL constants so callers can use domain-appropriate values
  TTL: {
    accounts: TTL_ACCOUNTS_MS,
    transactions: TTL_TRANSACTIONS_MS,
  },
};
