// Generated by GentleIA (OpenCode) — Phase 2: Auth

// ---------------------------------------------------------------------------
// Sensitive patterns — anything matching these will be replaced with [REDACTED]
// ---------------------------------------------------------------------------

const SENSITIVE_PATTERNS: RegExp[] = [
  /Bearer\s+[\w.-]+/gi,
  /access_token["\s:=]+[\w.-]+/gi,
  /refresh_token["\s:=]+[\w.-]+/gi,
  /password["\s:=]+"[^"]+"/gi,
];

function sanitize(value: string): string {
  let result = value;
  for (const pattern of SENSITIVE_PATTERNS) {
    result = result.replace(pattern, '[REDACTED]');
  }
  return result;
}

function sanitizeData(data: unknown): unknown {
  if (data === undefined || data === null) return data;
  if (typeof data === 'string') return sanitize(data);
  try {
    return JSON.parse(sanitize(JSON.stringify(data)));
  } catch {
    return '[SANITIZE_ERROR]';
  }
}

// ---------------------------------------------------------------------------
// Logger
// ---------------------------------------------------------------------------

export const logger = {
  info(message: string, data?: unknown): void {
    if (!__DEV__) return;
    const clean = sanitize(message);
    if (data !== undefined) {
      console.log(`[INFO] ${clean}`, sanitizeData(data));
    } else {
      console.log(`[INFO] ${clean}`);
    }
  },

  warn(message: string, data?: unknown): void {
    if (!__DEV__) return;
    const clean = sanitize(message);
    if (data !== undefined) {
      console.warn(`[WARN] ${clean}`, sanitizeData(data));
    } else {
      console.warn(`[WARN] ${clean}`);
    }
  },

  error(message: string, error?: unknown): void {
    // errors always log, even in production
    const clean = sanitize(message);
    if (error !== undefined) {
      console.error(`[ERROR] ${clean}`, sanitizeData(error));
    } else {
      console.error(`[ERROR] ${clean}`);
    }
  },
};
