// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { useState, useEffect } from 'react';

// ---------------------------------------------------------------------------
// NOTE: @react-native-community/netinfo is not installed in this project.
// This hook uses a lightweight workaround: it starts as online (true) and
// attempts a HEAD request to a reliable endpoint to verify connectivity.
// For production, install @react-native-community/netinfo and replace this
// implementation with the real NetInfo.addEventListener approach.
// TODO: conectar a NetInfo real cuando se instale @react-native-community/netinfo
// ---------------------------------------------------------------------------

const CONNECTIVITY_CHECK_URL = 'https://www.gstatic.com/generate_204';
const CHECK_INTERVAL_MS = 30_000; // recheck every 30 seconds

async function checkConnectivity(): Promise<boolean> {
  try {
    const response = await fetch(CONNECTIVITY_CHECK_URL, {
      method: 'HEAD',
      cache: 'no-store',
    });
    return response.ok || response.status === 204;
  } catch {
    return false;
  }
}

export function useNetworkStatus(): { isOnline: boolean } {
  const [isOnline, setIsOnline] = useState<boolean>(true);

  useEffect(() => {
    let cancelled = false;

    async function update(): Promise<void> {
      const online = await checkConnectivity();
      if (!cancelled) setIsOnline(online);
    }

    void update();

    const interval = setInterval(() => {
      void update();
    }, CHECK_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, []);

  return { isOnline };
}
