// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import type { Account, AccountType } from '@/types/index';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface AccountCardProps {
  account: Account;
  onPress: () => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatBalance(amount: number): string {
  return `S/ ${amount.toLocaleString('es-PE', { minimumFractionDigits: 2 })}`;
}

const TYPE_COLORS: Record<AccountType, string> = {
  checking: '#2563eb',   // blue
  savings: '#16a34a',    // green
  investment: '#7c3aed', // purple
};

const TYPE_LABELS: Record<AccountType, string> = {
  checking: 'Cuenta corriente',
  savings: 'Cuenta de ahorros',
  investment: 'Inversión',
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function AccountCard({ account, onPress }: AccountCardProps) {
  const accentColor = TYPE_COLORS[account.type];

  return (
    <TouchableOpacity
      style={[styles.card, { borderLeftColor: accentColor }]}
      onPress={onPress}
      activeOpacity={0.8}
      accessibilityRole="button"
      accessibilityLabel={`${account.name}, saldo ${formatBalance(account.balance)}`}
    >
      <View style={styles.header}>
        <Text style={styles.name} numberOfLines={1}>
          {account.name}
        </Text>
        <View style={[styles.typeBadge, { backgroundColor: accentColor }]}>
          <Text style={styles.typeText}>{TYPE_LABELS[account.type]}</Text>
        </View>
      </View>

      <Text style={[styles.balance, { color: accentColor }]}>
        {formatBalance(account.balance)}
      </Text>

      <Text style={styles.iban}>IBAN •••• {account.iban}</Text>
    </TouchableOpacity>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginVertical: 6,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  name: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    flex: 1,
    marginRight: 8,
  },
  typeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  typeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
  },
  balance: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
  },
  iban: {
    fontSize: 12,
    color: '#94a3b8',
    letterSpacing: 0.5,
  },
});
