// Generated by GentleIA (OpenCode) — Phase 4: Transfer & Cards

import { useEffect, useRef } from 'react';
import { Animated, StyleSheet, Text, TouchableOpacity } from 'react-native';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface InAppNotificationProps {
  message: string;
  type: 'success' | 'error';
  visible: boolean;
  onDismiss: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function InAppNotification({
  message,
  type,
  visible,
  onDismiss,
}: InAppNotificationProps) {
  const translateY = useRef(new Animated.Value(-120)).current;

  useEffect(() => {
    if (visible) {
      // Slide-down al aparecer
      Animated.spring(translateY, {
        toValue: 0,
        useNativeDriver: true,
        damping: 15,
        stiffness: 120,
      }).start();

      // Auto-dismiss después de 3 segundos
      const timer = setTimeout(() => {
        onDismiss();
      }, 3000);

      return () => {
        clearTimeout(timer);
      };
    } else {
      // Slide-up al desaparecer
      Animated.spring(translateY, {
        toValue: -120,
        useNativeDriver: true,
        damping: 15,
        stiffness: 120,
      }).start();

      return undefined;
    }
  }, [visible, onDismiss, translateY]);

  if (!visible) return null;

  const backgroundColor = type === 'success' ? '#16a34a' : '#dc2626';

  return (
    <Animated.View
      style={[
        styles.container,
        { backgroundColor, transform: [{ translateY }] },
      ]}
      accessibilityRole="alert"
      accessibilityLiveRegion="polite"
    >
      <TouchableOpacity
        style={styles.inner}
        onPress={onDismiss}
        activeOpacity={0.9}
        accessibilityLabel="Cerrar notificación"
      >
        <Text style={styles.icon}>{type === 'success' ? '✓' : '✕'}</Text>
        <Text style={styles.message} numberOfLines={2}>
          {message}
        </Text>
      </TouchableOpacity>
    </Animated.View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 999,
  },
  inner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  icon: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  message: {
    flex: 1,
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
});
