// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface LoadingStateProps {
  message?: string;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function LoadingState({ message }: LoadingStateProps) {
  return (
    <View style={styles.container}>
      <ActivityIndicator size="large" color="#2563eb" />
      {message ? <Text style={styles.message}>{message}</Text> : null}
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
  },
  message: {
    marginTop: 16,
    fontSize: 15,
    color: '#64748b',
    textAlign: 'center',
  },
});
