// Generated by GentleIA (OpenCode) — Phase 3: Dashboard

import { StyleSheet, Text, View } from 'react-native';
import type { Transaction } from '@/types/index';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface TransactionItemProps {
  transaction: Transaction;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatAmount(amount: number, type: Transaction['type']): string {
  const sign = type === 'credit' ? '+' : '-';
  return `${sign} S/ ${amount.toLocaleString('es-PE', { minimumFractionDigits: 2 })}`;
}

function formatDate(isoDate: string): string {
  const date = new Date(isoDate);
  return date.toLocaleDateString('es-PE', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function TransactionItem({ transaction }: TransactionItemProps) {
  const amountColor = transaction.type === 'credit' ? '#16a34a' : '#dc2626';

  return (
    <View style={styles.container}>
      <View style={styles.left}>
        <Text style={styles.description} numberOfLines={1}>
          {transaction.description}
        </Text>
        <Text style={styles.category}>{transaction.category}</Text>
        <Text style={styles.date}>{formatDate(transaction.date)}</Text>
      </View>

      <Text style={[styles.amount, { color: amountColor }]}>
        {formatAmount(transaction.amount, transaction.type)}
      </Text>
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#ffffff',
  },
  left: {
    flex: 1,
    marginRight: 12,
  },
  description: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: 2,
  },
  category: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 2,
  },
  date: {
    fontSize: 11,
    color: '#94a3b8',
  },
  amount: {
    fontSize: 14,
    fontWeight: '700',
  },
});
